# Header
menu:
  Home: /
  Archives: /archives
  About: /About
  GitHub: https://github.com/lessmind
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: true
widgets:
- recent_posts
- category
- tag
# - tagcloud
- archive

# Miscellaneous
google_analytics: UA-68626281-1
google_adsense: ca-pub-7758453423688329
favicon:
twitter: nevermindChao
google_plus:
fb_admins:
fb_app_id: